CREATE TABLE IF NOT EXISTS public.endpoints (
    id text NOT NULL,
    active boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by text,
    updated_by text,
    deleted_at timestamp with time zone,
    deleted_by text,
    type text,
    backend_id text,
    policy_id text,
    interceptor_id text,
    response_transformer_id text,
    request_validator_id text,
    path text,
    method text,
    skip_activity_log boolean,
    allowed_headers text,
    allowed_response_headers text,
    sql_statement text,
    javascript text,
    response text,
    request_timeout bigint,
    rate_limit bigint,
    rate_limit_type text,
    description text,
    enable_cors boolean,
    allow_origins text,
    allow_headers text,
    allow_credentials boolean,
    expose_headers text,
    max_age bigint,
    allow_private_network boolean,
    grpc_service text,
    webhook_url text
);
