CREATE TABLE IF NOT EXISTS public.backends (
    id text NOT NULL,
    active boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by text,
    updated_by text,
    deleted_at timestamp with time zone,
    deleted_by text,
    type text,
    name text,
    protocol text,
    host text,
    authentication_type text,
    authentication_location text,
    username text,
    password text,
    client_id_key text,
    client_id_value text,
    client_token_key text,
    client_token_value text,
    database text,
    is_deployed boolean DEFAULT false,
    message_id bigint,
    chat_id bigint,
    ssl_cert text,
    ssl_key text,
    protobuf text,
    verify_ssl boolean,
    enable_circuit_breaker boolean,
    cb_max_requests bigint,
    cb_interval bigint,
    cb_timeout bigint,
    cb_minimum_http_code bigint
);
